project:
  type: website
  output-dir: docs
website:
  #title: "Theo Anim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: /media/TheoAnimResume.pdf
        text: Resume
      - href: News.qmd
        text: Highlights
format:
  html:
    theme: zephry
    css: styles.css
    toc: true
    page-layout: full
    



