{
  "hash": "9324547c13c68f96469253ef7e89ebcc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bayesian Modeling for the Detection of Adverse Events Underreporting in Clinical Trials\"\nformat: \n  html:\n    toc: true\n    toc-location: right\n    css: justify.css\n    number-sections: false\n    fig-cap-location: bottom\n    fig-cap: true\n    fig-numbering: true\n    table-caption: true\n    citations: true\n    citation-location: document\n    citation-style: van.csl\nbibliography: aeref.bib \ncode-fold: true\n---\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n################libraries################\nlibrary(tidyverse)\nlibrary(rjags)\nlibrary(bayesplot)\nlibrary(kableExtra)\nlibrary(MCMCvis)\n```\n:::\n\n\n# Introduction\n\nCount data underreporting is prevalent in many fields and clinical trial is no exception. According to Seruga et. al (2016) substantial evidence shows clinicians underreport harm in clinical trial. Underreporting can be in the form of non-representative of patient's experience by clinicians or inaccurate reporting of detected adverse events.[@seruga2016under] underreporting poses risk to patient safety and data integrity.[@barmaz2021bayesian] Efforts have been made to model adverse events underreporting using Machine Learning framework[@menard2019enabling] and Bayesian Methods.[@barmaz2021bayesian] Traditional site inspection for clinical trial is not feasible in the case of multiple sites. Modeling adverse safeguard patients' safety.  Data driven approach like we present here reduce the need for onsite visits and manual quality assurance activities.  \n\nThis blog post is based on the original works of [Yves Barmas and Menard Timothe](https://pmc.ncbi.nlm.nih.gov/articles/PMC8278191/) and it is intended to provide a tutorial on how to model adverse events under Bayesian framework. The implementation in this blog is done in R. \n\n# Methodology \n\nThe primary objective is to develop a robust method to assess the risk of AE underreporting from study sites[@barmaz2021bayesian]. Specifically, we use Bayesian hierarchical model to infer site reporting rates and the risk of underreporting. Bayesian models relies on the application of Bayes theorem:\n$$p(\\boldsymbol{\\theta}| \\mathbf{x}) \\propto l(\\mathbf{x}\\boldsymbol|{\\theta})p(\\boldsymbol{\\theta})$$\n\nThat is, we model the posterior as proportional to the likelihood and the prior distribution on $\\boldsymbol{\\theta}$. We usually think of the posterior distribution as an update of the prior after incorporating the observed data. In the case of count data, the likelihood can be derived using a poisson or negative binomial distribution. Unlike a poisson process where the mean and variance are equal, a negative binomial allows for over-dispersion. The Bayesian approach is an improvement on machine learning approach for modeling adverse events underreporting.[@menard2019enabling]\n\n\n\n# Data Description\n\nThe data originates from the control arm of a Phase III, Randomized Double-Blind placebo-controlled study to access the efficacy and safety of 10mg Zibotetntan with Docetaxel in Metastics Hormone resistant Prostate Cancer.[@fizazi2013phase] The primary endpoint of the study was to compare overall survival of Zibotentan combined with docetaxel to docetaxel. The data can be found [here](https://github.com/ybarmaz/bayesian-ae-reporting/blob/main/data.csv).\n\nThe data includes site number, patient random identifier and adverse event count. There are 125 unique sites and 468 patients whose adverse event counts are recorded.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ninputdf <- df |> \n  select(site_number, patnum, ae_count_cumulative) |>\n  group_by(site_number) |>\n  summarise(aes_count = str_c(\"(\", str_c((\n    ae_count_cumulative\n  ), collapse = \", \"), \")\"),\n  Number_of_patients = n_distinct(patnum))\n\ninputdf |>\n  head(8) |>\n  kable(caption = \"Sample of input data\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sample of input data\n\n| site_number|aes_count                | Number_of_patients|\n|-----------:|:------------------------|------------------:|\n|        3001|(4, 1)                   |                  2|\n|        3002|(2, 2, 1, 2, 5, 5, 5, 1) |                  8|\n|        3003|(7, 4)                   |                  2|\n|        3004|(3, 27, 8)               |                  3|\n|        3005|(12, 6)                  |                  2|\n|        3006|(2, 4)                   |                  2|\n|        3007|(5)                      |                  1|\n|        3008|(11, 4, 16, 31, 23, 23)  |                  6|\n\n\n:::\n:::\n\n\nWe see the number of patients at each site and their corresponding reported adverse events. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nout <- df |>\n  group_by(ae_count_cumulative) |>\n  summarise(frequency = n()) |>\n  rename(ae_count = ae_count_cumulative)\n\n\nggplot(out, aes(x = as.factor(ae_count), y = frequency)) +\n  geom_col(fill = \"tan\", color = \"black\") +\n  labs(x = \"adverse event counts\") +\n  guides(x = guide_axis(check.overlap = TRUE))\n```\n\n::: {.cell-output-display}\n![Frequency of adverse events](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-3-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nWe can observe from the plot that 24 patients experienced no adverse events.\n\n\n# Poisson hierarchical model\n\nThe number of adverse event for a patient from the $i^{th}$ site is modeled as Poisson hierarchy.[@barmaz2021bayesian]\n$$Y_{1}, Y_{2}, \\dots, Y_{n_i} \\sim Poisson(\\lambda_{i})$$\n$n_{i}$ denotes the number of patients at a specific site\n\n$\\lambda_{i}, i = 1, 2, \\dots, N_{sites}$ is drawn from a single study level gamma distribution, $\\Gamma(\\mu_{study}, \\sigma_{study})$ with $exp(0.1)$ as vague hyperpriors on mean and standard deviation. This reparametrization gives a more direct interpretation of the posterior of $\\mu$ as the average reporting rate across sites and $\\sigma$ as the measure of variability in the reporting rate across sites.\n\nThe data is well represented in Figure 1.\n\n::: {.cell}\n::: {.cell-output-display}\n![Graphical representation of the adverse event reporting model](AE-Underreporting-reveal-JS_files/figure-html/fig-adverse-event-model-tikza-1.png){#fig-adverse-event-model-tikza fig-pos='center' width=288}\n:::\n:::\n\n\nThe use of a hierarchical Poisson model requires prior justification for study mean and standard deviation. One can justify the choice of hyperpriors by considering the prior predictive distribution. Here, the prior predictive distribution for the choice of priors have similar range as the observed adverse event counts.\n\n::: {.cell}\n\n```{.r .cell-code}\n###################################################\n################model description##################\n###################################################\nset.seed(2)\nadv <- \"\nmodel{\n  for(i in 1:N){\n    y[i] ~ dpois(rates[site_idx[i]])\n  }\n  \n  ##### prior\n  for(j in 1:J){\n       rates[j] ~ dgamma(shape, rate)\n  }\n  \n  ###Hyperpriors on rate################\n  mu ~ dexp(0.1)\n  sigma ~ dexp(0.1)\n  \n  #transformation to shape and rate of gamma\n  rate <- mu/sigma^2\n  shape <- mu^2/sigma^2\n  \n  ####a random rate is less than site's rate\n  reference_rate ~ dgamma(shape, rate)\n  for(j in 1:J){\n     underreporting[j] <- reference_rate < rates[j]\n  }\n}\n\"\nwriteLines(adv, \"adversevents.txt\")\n```\n:::\n\n\n### Prior predictive distribution\n\nTo simulate the prior predictive distribution in Jags, use NAs for the data nodes. The prior predictive checks shows what data-sets would be consistent with the prior distribution. Recall that the priors used are vague.\n\n::: {.cell}\n\n```{.r .cell-code}\n#####################prior predictive################\n#####################################################\nset.seed(2)\nmissg <- list(\n  y = rep(NA, nrow(df)),\n  N = nrow(df),\n  J = length(unique(df$site_number)),\n  site_idx = as.numeric(factor(df$site_number))\n)\n\nppd_model <- jags.model(\n  file = \"adversevents.txt\",\n  data = missg,\n  n.chains = 3,\n  quiet = TRUE\n)\nupdate(ppd_model, 1e3)\nprior_pred <- coda.samples(\n  ppd_model,\n  variable.names = c(\"y\"),\n  n.iter = 8e3\n)\nprior_pred <- as.vector(prior_pred[[1]]) #simulated y's into a vector\nsample_prior_pred <- sample(prior_pred, 100) # sample a few to plot\n\ntibble(prior_predictive = sample_prior_pred) |>\n  group_by(prior_predictive) |>\n  summarise(frequency = n()) |>\n  ggplot(aes(x = as.factor(prior_predictive), y = frequency)) +\n  geom_col(fill = \"tan\", color = \"black\") +\n  labs(x = \"prior predictive distribution\") +\n  guides(x = guide_axis(check.overlap = TRUE))\n```\n\n::: {.cell-output-display}\n![](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-5-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nTo quantify the risk of underreporting, we compute a left tail area probability defined as\n$$RTA_{i} = P(\\hat{\\lambda} < \\hat{\\lambda}_{i})$$\nWe interpret this as posterior probability that a randomly selected reporting rate from the posterior distribution is below a site's inferred reporting rate.\n\n### Posterior distribution\n\nRun the MCMC algorithm with 1000 burn-in,  3 chains and 8000 samples for each chain. \n\n::: {.cell}\n\n```{.r .cell-code}\n##################Observed data###############################\ndata <- list(\n  y = df$ae_count_cumulative,\n  N = nrow(df),\n  J = length(unique(df$site_number)),\n  site_idx = as.numeric(factor(df$site_number))\n)\n\nmodel <- jags.model(\n  file = \"adversevents.txt\",\n  data = data,\n  n.chains = 3,\n  quiet = TRUE\n)\nupdate(model, 1e3)\n\n############posterior distribution############################\nsamples <- coda.samples(\n  model,\n  variable.names = c(\"mu\", \"sigma\", \"rates\", \"underreporting\"),\n  n.iter = 8e3\n)\n```\n:::\n\n\n# Results and Discussion\n\nBefore making inference from the results of MCMC algorithms, we need to check the quality of the generated sample. MCMC diagnostics tool helps us to determine whether generated posterior distribution represents an accurate approximation of the target posterior.\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_trace(samples, pars = c(\"mu\", \"sigma\", \"rates[1]\", \"rates[2]\"))\n```\n\n::: {.cell-output-display}\n![convergence diagnostics](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-7-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nWe see a \"good\" mixing in the chains. That is, the plots of the individual chains merge. Well-behaved chains results in a smooth histogram(density) of the posterior distribution.\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_hist(\n  samples,\n  pars = c(\n    \"mu\",\n    \"sigma\",\n    \"rates[30]\",\n    \"rates[100]\",\n    \"underreporting[30]\",\n    \"underreporting[100]\"\n  ),\n  facet_args = list(nrow = 2)\n)\n```\n\n::: {.cell-output-display}\n![Histogram of Posterior](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-8-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nThe MCMC diagnostics reveal no issues so we can go ahead with inference. Notice that site 3030 seems suspicious with low reporting compared to site 3100.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutput <- MCMCsummary(samples, params = c(\"mu\", \"sigma\", \"rates\"))\nhead(output, 5) |> kable(caption = \"Posterior summaries\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n\nTable: Posterior summaries\n\n|         |   mean|    sd|   2.5%|    50%|  97.5%| Rhat| n.eff|\n|:--------|------:|-----:|------:|------:|------:|----:|-----:|\n|mu       | 14.878| 1.022| 12.999| 14.836| 16.986|    1|  3695|\n|sigma    | 11.138| 1.056|  9.281| 11.077| 13.390|    1|  3555|\n|rates[1] |  3.203| 1.225|  1.265|  3.045|  6.012|    1| 23744|\n|rates[2] |  3.056| 0.616|  1.972|  3.016|  4.374|    1| 24353|\n|rates[3] |  6.039| 1.690|  3.173|  5.880|  9.775|    1| 24983|\n\n\n:::\n:::\n\n\nThe table above presents the posterior summaries of the study mean, study standard deviation and reporting rates. Also included are the 95% credible interval, median, Gelman Rubin statistic and the effective sample size. Larger values of SD suggests uncertainty about the estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrate_tail_area <- MCMCsummary(samples, params = \"underreporting\")\nrta_summary <- tibble(\n  site = unique(df$site_number),\n  mean_ae_rate = output[-c(1:2), ]$mean,\n  sd_ae_rate =  output[-c(1:2), ]$sd,\n  rate_tail_area = rate_tail_area$mean,\n  aes_count = inputdf$aes_count\n)\n\narrange(rta_summary, rate_tail_area) |>\n  head(8) |>\n  kable(caption = \"Posterior summaries of AE rate and Rate tail area for each site\", digits = 3)\n```\n\n::: {.cell-output-display}\n\n\nTable: Posterior summaries of AE rate and Rate tail area for each site\n\n| site| mean_ae_rate| sd_ae_rate| rate_tail_area|aes_count                      |\n|----:|------------:|----------:|--------------:|:------------------------------|\n| 3030|        0.475|      0.218|          0.004|(0, 0, 0, 1, 0, 0, 0, 0, 0, 2) |\n| 3036|        0.921|      0.478|          0.014|(0, 1, 0, 1)                   |\n| 3037|        1.326|      0.509|          0.024|(1, 0, 1, 3, 0)                |\n| 3046|        1.601|      1.209|          0.035|(0)                            |\n| 3032|        2.259|      1.031|          0.054|(3, 0)                         |\n| 3035|        2.269|      1.050|          0.056|(0, 3)                         |\n| 3018|        2.619|      0.795|          0.068|(6, 1, 2, 0)                   |\n| 3039|        2.735|      1.129|          0.073|(3, 1)                         |\n\n\n:::\n:::\n\n\nThis table shows the study sites of the top 8 lowest rate tail area. Site 3046 has a 0 reported adverse event yet the mean ae rate is thrice larger than the mean ae rate for site 3030, which can be attributed to the information sharing across study sites. The uncertainty around the estimate is quiet high compared to site 3030.\n\nWith a well-defined threshold, clinicians can flag sites with lower rate tail area. If we chose a 0.05 threshold then site 3030 could be flagged as potential site with underreporting; prompting clinicians to focus on this site.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(rta_summary)+\n  geom_point(aes(mean_ae_rate, rate_tail_area))\n```\n\n::: {.cell-output-display}\n![Rate tail area versus posterior mean of site rate](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-11-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nThis graph represents the empirical posterior predictive cumulative distribution. Lower expected adverse event rate is associated with lower reporting probability.\n\n\n# Other MCMC Checks\n\nIn the following steps we offer other due diligence checks for convergence of the MCMC algorithm\n\n::: {.cell}\n\n```{.r .cell-code}\ngelman.plot(samples[, c(\"mu\",\n                        \"sigma\",\n                        \"rates[1]\",\n                        \"rates[2]\",\n                        \"rates[50]\",\n                        \"rates[100]\")], ncol = 2)\n```\n\n::: {.cell-output-display}\n![Gelman plot](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-12-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nThe Brook-s Gelman Rubin diagnostic plots should approach one, which is what we see in the plots above. The Gelman plots often requires at least two chains.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_pairs(\n  samples,\n  pars = c(\"mu\", \"sigma\", \"rates[1]\", \"rates[2]\"),\n  diag_fun = \"dens\"\n)\n```\n\n::: {.cell-output-display}\n![Pairs plot of posterior samples](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-13-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nBivariate plots for each pair of parameters need to be examined as it is possible for parameters to be dependent a posteriori even for priors taken to be independent. Dependent posterior can lead to problematic inference. The mean and sigma posterior are correlated(Not too surprising since we know the mean and variance of a poisson to be equal). Our inference makes no use of marginal posterior of $\\mu$ and $\\sigma$. The posterior site rates which are used for inference in this reported  are clearly uncorrelated.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmcmc_acf(samples, pars = c(\"mu\", \"sigma\", \"rates[1]\", \"rates[2]\"))\n```\n\n::: {.cell-output-display}\n![Autocorrelation plot posterior samples](AE-Underreporting-reveal-JS_files/figure-html/unnamed-chunk-14-1.png){fig-pos='center' width=672}\n:::\n:::\n\n\nAutocorrelation plots of interested parameters should decrease rapidly. Here, the reporting rates have a quick decline in autocorrelation.\n\n\n\n\n# Conclusion\n \nIn this post, we reproduced the work of Yves Barmaz and Timothé Ménard. Bayesian modeling of adverse event counts have been used to quantify the risk of AE underreporting. Sites with potential AEs underreporting can be flagged for onsite audits and thorough data verification. \n\n# Limitation\n\nThe time structure associated with the the occurrence of the adverse events is ignored in this analysis. Covariates that can influence the occurrence of adverse events are also ignored. In situations where the site level data is overdispersed, the current implementation is inadequate. We may need to consider negative binomial in place of the poisson model.\n\n\n## Disclaimer\n\n- This post was born out of a requirement to reproduce and present a published article in our Bayesian Theory class.\n\n- A special thank you to Barmaz Y and Ménard T for the permission to reproduce their paper.",
    "supporting": [
      "AE-Underreporting-reveal-JS_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}